Update config.yml
added workspace

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,29 +5,40 @@ jobs:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
-      - run: echo "A First Hello"
-      - run: sleep 5
+      - run: mkdir -p my_workspace
+      - run: echo "Hello World" > my_workspace/echo-output
+      - persist_to_workspace:
+          root: my_workspace
+          paths:
+            - echo-output
   testa:
     docker:
      - image: circleci/ruby:2.4.1
     steps:
-     - checkout
-     - run: echo " A more familiar hi"
-     - run: sleep 5
+     - attach_workspace:
+         at: my_workspace
+     - run: cat my_workspace/echo_output
   testb:
     docker:
      - image: circleci/ruby:2.4.1
     steps:
-     - checkout
-     - run: echo " A locallized Salut"
-     - run: sleep 5
+     - attach_workspace:
+          at: my_workspace
+     - run: |
+          # This will fail internallly, we will use SSH to debug and fix
+          if [[ $(cat my_worspace/echo_output) == "Trying out workspaces" ]]; then
+            echo "It worked!";
+          else
+            echo "Nope!"; exit 1
   deploy:
     docker:
      - image: circleci/ruby:2.4.1
     steps:
-     - checkout
-     - run: echo " A final Goodbye"
-     - run: sleep 5
+     - attach_workspace:
+        at: my_workspace
+     - run: |
+          echo "Deploying message"
+          cat my_workspace/echo_outpu
      
 workflows:
  version: 2
